version: "3.8"

services:
  app:
    extends:
      file: docker-compose.yaml
      service: app
    environment:
      - NODE_ENV=staging
    ports:
      - ${BIND_PORT:-9998}:9991
    labels:
      - "traefik.http.middlewares.shipwrecked-staging-auth.basicauth.users=a:$2y$05$QTXagpNFoBfdnI8oCQ7.5eHyadpbg8YGK6p9Y7.640H.bWvCIbycu"
      - traefik.http.routers.https-0-gwkso00g48gwsk044owcs4gw-app.entryPoints=https, shipwrecked-staging-auth
